from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.writeback.adapters.base import BaseWritebackAdapter
from app.writeback.types import DeliveryResult


class ClayWritebackAdapter(BaseWritebackAdapter):
    target_type = "clay"

    def deliver(
        self,
        payload: dict[str, Any],
        endpoint_url: str | None,
        timeout_seconds: int = 15,
        **kwargs: Any,
    ) -> DeliveryResult:
        auth_headers = kwargs.get("auth_headers")
        simulate_local = bool(kwargs.get("simulate_local", False))
        if simulate_local:
            # Local simulation artifacts are intentionally disabled.
            raise ValueError("Clay simulate_local mode is disabled. Provide a real endpoint_url.")

        if not endpoint_url:
            return DeliveryResult(
                status="success",
                response_json={
                    "delivery_mode": "stub",
                    "target_type": self.target_type,
                    "message": "No Clay endpoint configured; recorded deterministic stub success",
                },
            )
        return self._post_json_with_headers(
            endpoint_url=endpoint_url,
            payload=payload,
            timeout_seconds=timeout_seconds,
            headers=auth_headers if isinstance(auth_headers, dict) else None,
        )

    def _deliver_simulated_local(self, payload: dict[str, Any], writeback_run_id: str) -> DeliveryResult:
        # Legacy simulation helper retained for possible future feature-flag reintroduction.
        root = Path(__file__).resolve().parents[3]
        outbound_dir = root / "data" / "outbound" / "clay_requests"
        inbound_dir = root / "data" / "inbound" / "clay_results"
        outbound_dir.mkdir(parents=True, exist_ok=True)
        inbound_dir.mkdir(parents=True, exist_ok=True)

        account_id = payload.get("account_id", "unknown")
        ts = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        slug = f"run_{writeback_run_id}_account_{account_id}_{ts}"

        outbound_file = outbound_dir / f"{slug}.json"
        outbound_file.write_text(json.dumps(payload, indent=2), encoding="utf-8")

        normalized_result = self._build_simulated_enrichment(payload=payload, writeback_run_id=writeback_run_id)
        inbound_file = inbound_dir / f"{slug}_result.json"
        inbound_file.write_text(json.dumps({"results": [normalized_result]}, indent=2), encoding="utf-8")

        return DeliveryResult(
            status="success",
            response_json={
                "delivery_mode": "simulated_local",
                "target_type": self.target_type,
                "outbound_file": str(outbound_file),
                "generated_inbound_result_file": str(inbound_file),
                "result_count": 1,
            },
            external_key=f"simulated-clay-{writeback_run_id}-{account_id}",
        )

    def _build_simulated_enrichment(self, payload: dict[str, Any], writeback_run_id: str) -> dict[str, Any]:
        company_name = str(payload.get("company_name") or "")
        domain = str(payload.get("domain") or "")
        account_id = int(payload.get("account_id") or 0)
        intent_score = float(payload.get("latest_intent_score") or 0)
        weak_reasons = payload.get("weak_match_reasons") or []
        if not isinstance(weak_reasons, list):
            weak_reasons = [str(weak_reasons)]

        # Deterministic enrichment banding from account id.
        band_index = account_id % 4
        employee_band = ["11-50", "51-200", "201-500", "501-1000"][band_index]
        hq_country = ["United States", "Canada", "United Kingdom", "Germany"][band_index]
        industry_hint = "B2B SaaS" if "data" in company_name.lower() or "analytics" in company_name.lower() else "Technology"

        return {
            "target_type": "clay",
            "entity_type": "account",
            "entity_id": account_id,
            "enrichment_type": "firmographic_refresh",
            "normalized_data_json": {
                "company_name": company_name,
                "domain_confirmed": domain,
                "industry_refined": industry_hint,
                "employee_band": employee_band,
                "hq_country": hq_country,
                "intent_score_context": intent_score,
                "confidence_notes": {
                    "source": "simulated_clay",
                    "weak_match_reasons": weak_reasons,
                    "resolution_hint": "Review CRM contact ownership and LinkedIn URLs for higher-confidence matching.",
                },
            },
            "source_run_id": writeback_run_id,
            "notes": "Generated by simulated Clay adapter for local demo round-trip",
        }
